### ISSUE TITLE
Fix transient spec failures

### ISSUE THREAD

**Issue by johnnyshields** [tablecheck/mongoid-ultra#12]
https://github.com/tablecheck/mongoid-ultra/actions/runs/4660431192/jobs/8248482848?pr=9

```
  1) Mongoid::Clients::Options.with when passing some options when passing a block when the options create a new cluster disconnects the new cluster when the block exits
     Failure/Error: expect(connections_after).to eq(connections_before)
     
       expected: 6
            got: 7
     
       (compared using ==)
     # ./spec/mongoid/clients/options_spec.rb:430:in `block (6 levels) in <top (required)>'
     # ./spec/shared/lib/mrss/lite_constraints.rb:232:in `block in retry_test'
     # ./spec/lite_spec_helper.rb:74:in `block (3 levels) in <top (required)>'
     # ./spec/lite_spec_helper.rb:73:in `block (2 levels) in <top (required)>'
```

**Comment by johnnyshields** [comment]
Fixed
